apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: clusterissuer
spec:
  acme:
    email: name@example.com
    privateKeySecretRef:
      name: letsencrypt-clusterissuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
