# https://kube-vip.io/docs/installation/static/
# service.metadata.annotations["kube-vip.io/loadbalancerIPs"]: 10.1.0.200
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_loglevel
      value: "4"
    - name: vip_arp
      value: "true"
    - name: svc_enable
      value: "true"
    image: ghcr.io/kube-vip/kube-vip:v0.8.6
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        - SYS_TIME
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
